Feat: check guestCount valid with activating button
Dont12/KDT_Y_FE_Mini-Project pull request #72
Opened 2023-11-29 11:38 UTC by HOOOO98

## 작업 내용
숙박할 게스트 수와 최대 정원과의 비교
디테일 타입 변경 적용

close #63

2023-11-29 13:08 UTC, NamgungJongMin requested changes
타입 대문자 해주세요.

2023-11-29 13:08 UTC, NamgungJongMin commented on src/components/detail/CartButton.tsx
> +import { isCartPropsValid, PushCartResponse } from '@/@types/cart.types';
타입명 대문자로 바꿔주세요.

2023-11-29 16:27 UTC, jseo9732 approved these changes
고생하셨습니다

2023-11-29 16:27 UTC, jseo9732 commented on src/api/cartRequest.ts
> +const url = 'https://api.stayinn.site/v1';
성후님 이거 작동안돼서 다시 되돌려 놓으신거면
.env.local 파일은 `NEXT_PUBLIC_SERVER_URL`로 하고

여기 코드는 `process.env.NEXT_PUBLIC_SERVER_URL`로 수정하시면 정상 작동할 겁니다

❗️환경변수에 `NEXT_PUBLIC_` 붙여야함

2023-11-29 16:27 UTC, jseo9732 commented on src/components/detail/PersonInput.tsx
>      );
👍👍👍

2023-11-30 01:00 UTC, HOOOO98 commented on src/api/cartRequest.ts
> +const url = 'https://api.stayinn.site/v1';
네!!! 진짜 감사합니다!!

2023-11-30 01:04 UTC, HOOOO98 commented on src/api/cartRequest.ts
> +const url = 'https://api.stayinn.site/v1';
서버키도 관리하는게 맞을까요??ㅠㅠ
변수로 관리하면 한번에 관리할 떄 편하긴 할 거 같은데
어떻게 생각하시나요??

2023-11-30 01:08 UTC, HOOOO98 commented on src/components/detail/KakaoMap.tsx
> +const JSKey = process.env.NEXT_PUBLIC_KAKAOMAP_JSKEY;
@jseo9732 우선 환경변수 키 바꿔봤습니다~
서버도 키로 관리하는 게 맞는지 모르겠어요ㅠㅠ
변수에 넣을까요??

2023-11-30 04:24 UTC, NamgungJongMin approved these changes

2023-11-30 06:26 UTC, merged